Module: Fotostatur
Version: 1.0
Description: Photo/image rating and profile posting app

Inputs:
  
  - Parameter: TwitterConsumerKey
    Scope: ImageAnalyzer
    Default: AQICAHhAYp3MoGsmyw6PKfGJGx5gZ7MuLIwCE75+PRPZdhkQVwEDhEqJzlaQGwZUWZerfCIFAAAAdzB1BgkqhkiG9w0BBwagaDBmAgEAMGEGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+/fnumFUW9H8JJi6AgEQgDTOukfdPD57H651Yy55uZjq96Be8z7670X3BNDME27LExz6j9DREsd2M9l6JEKsCZ9V86W2
    Type: Secret
  
  - Parameter: TwitterConsumerSecret
    Scope: ImageAnalyzer
    Default: AQICAHhAYp3MoGsmyw6PKfGJGx5gZ7MuLIwCE75+PRPZdhkQVwH0GD3W4G2drXZoBWQlT2GfAAAAkjCBjwYJKoZIhvcNAQcGoIGBMH8CAQAwegYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxC+5xsx0vgvLaLnFoCARCATd+svlQmfd7dSgrHstvtHtX9TXPsAUJ/PaadrGDqkwlpN3IAc13QwLB0//CRK1ZGUxMXT4gbzMQn4fcST8fyIEymBDMn5+80+Ssnqb7Q
    Type: Secret
  
  - Parameter: TwitterAccessToken
    Scope: ImageAnalyzer
    Default: AQICAHhAYp3MoGsmyw6PKfGJGx5gZ7MuLIwCE75+PRPZdhkQVwFtjA2DokGDDtacZgupf1TMAAAAkjCBjwYJKoZIhvcNAQcGoIGBMH8CAQAwegYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxdmxj1fsNyy1u9SogCARCATR/A1YZdcGGcqNhmQjcAepHDmDXeiSFwyzgXfukk82kugNPjn1qxg5tsx0JBYWzpcXT2nIc26ExcQH8CZEa0q/kq5gro9AY8papA+Ggq
    Type: Secret

  - Parameter: TwitterAccessSecret
    Scope: ImageAnalyzer
    Default: AQICAHhAYp3MoGsmyw6PKfGJGx5gZ7MuLIwCE75+PRPZdhkQVwGpKGumzHpgp/jyYFML/XgFAAAAjDCBiQYJKoZIhvcNAQcGoHwwegIBADB1BgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAqAohvOzFnhBsU9VgIBEIBIcuzuOpYlghd2fu5qiNs0LV6arJLrFve38teZna7T5itvIWMziIzXyK8kAdth5a7m8CPmRYGbSAqZ4+pOfsgGXaXtqqwXhnk2
    Type: Secret
    
  - Parameter: HeadshotFileName
    Scope: ImageAnalyzer
    Default: pattysrekogition.jpg
    Type: String

Variables:

  - Var: RekognitionPermission
    Value: "*"
    Resource:
      Type: AWS::IAM::Role
      Allow:
      - rekognition:DetectLabels
      - rekognition:DetectFaces
      - rekognition:CompareFaces
      - rekognition:DetectText

  - Var: FotostaturPhotoBucket
    Description: Where the photos will be stored
    Resource:
      Type: AWS::S3::Bucket
      Allow: ReadWrite

  - Var: HeadshotPhotos
    Package: HeadshotPhotos
    Files: Headshots
    Prefix: headshots/
    Bucket: FotostaturPhotoBucket
    Scope: ImageAnalyzer
    
    # TODO: Clean S3 bucket on delete
    
Functions:

  - Function: ImageAnalyzer
    Description: Bucket to process the image
    Memory: 128
    Timeout: 120
    Sources:
    - S3: FotostaturPhotoBucket
      Events:
      - "s3:ObjectCreated:*"
      Prefix: images/
      Suffix: .jpg
